osx_image: xcode8.2
language: objective-c
before_install:
- pod repo update > /dev/null
- pod install
script:
- set -o pipefail
- xcodebuild build test -workspace HRLApp.xcworkspace -scheme HRLApp -sdk iphonesimulator10.2 -destination 'platform=iOS Simulator,name=iPhone 5,OS=10.0' | xcpretty
after_success:
- bash <(curl -s https://codecov.io/bash)

